#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'MercurySDK_Example' do
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MercuryQNSDK', :path => '../'
#  pod 'AdvanceSDK', '~> 3.2.6.0' # 可指定你想要的版本号
#pod 'MSMobAdSDK/MS'
#  pod 'AdvanceSDK/Mercury','~> 3.1.7.0'  # 必须添加
#  pod 'AdvanceSDK/CSJ'     # 必须添加
#  pod 'AdvanceSDK/GDT'     # 必须添加
#  pod 'AdvanceSDK/BD' # 如果需要导入百青藤SDK 如果不需要则不添加 看需求选择是否添加
# pod  'AdvanceSDK/KS' # 如果需要导入快手广告则添加 如果不需要则不添加 看需求选择是否添加
#pod 'Ads-CN', '~> 4.5.1.6'
#pod 'GDTMobSDK', '~> 4.13.70'
#pod 'SJVideoPlayer'

#  pod 'AdvanceSDK'
#  pod 'AdvanceSDK/Mercury'
#  pod 'MercurySDK','~> 3.1.7.0'

#  pod 'AdvanceSDK/CSJ'     # 必须添加
#  pod 'AdvanceSDK/GDT'     # 必须添加
#  pod 'AdvanceSDK/BD' # 如果需要导入百青藤SDK 如果不需要则不添加 看需求选择是否添加
# pod  'AdvanceSDK/KS' # 如果需要导入快手广告则添加 如果不需要则不添加 看需求选择是否添加


  target 'MercurySDK_Tests' do
    inherit! :search_paths

    
  end
end
