#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'MercurySDK_Example' do
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MercuryQNSDK', :path => '../'

  target 'MercurySDK_Tests' do
    inherit! :search_paths

    
  end
end
